### ISSUE TITLE
qemu options for virtiofs evaluation

### ISSUE THREAD

**Issue by mmisono** [astrynzha/unikraft_9p_measure#1]
Hi @astrynzha,

Thanks for sharing the code. I'm interested in evaluating the fs performance of unikraft.
I can find the qemu script for [9p](https://github.com/astrynzha/unikraft_9p_measure/blob/master/launch.sh) but I wonder how you launched qemu to evaluate [viriofs](https://github.com/astrynzha/virtiofs_unikraft) and others in your [thesis](https://drive.google.com/file/d/1453lly-Q2c3RjfbIDkTUd-Knvk4T6n8k/view?usp=share_link).

**Comment by astrynzha** [comment]
Hello @mmisono,

Thanks for your comment. I'll take a look at how I did it tonight.

**Comment by astrynzha** [comment]
@mmisono A few things came up, I'll try to get back to you till Monday

**Comment by mmisono** [comment]
Thank you very much for your help.

Also, I have another question. In my understanding, currently, vfscore integration is incomplete and we need to call APIs defined in [ukfuse](https://github.com/astrynzha/virtiofs_unikraft/blob/master/lib/ukfuse/exportsyms.uk) to use virtiofs. I wonder if you find any difficulties in supporting vfscore (e.g., some feature support of viritofs is missing).

**Comment by astrynzha** [comment]
@mmisono
With regards to your first post:

For 9pfs and native Linux the benchmark code is in this ([unikraft_9p_measure](https://github.com/astrynzha/unikraft_9p_measure)) repo. All the measurements are run in the /guest_fs/ directory, so before running the benchmarks I mount it as tmpfs using `sudo mount -t tmpfs -o size=2G tpfs guest_fs` (or any other size).

For 9pfs I first do the standard `make menuconfig` in the directory with the contents of this repo, followed by `make`, in order to build the unikernel. The unikernel image then lands in this directory in /build/ and is called '06-adding-filesystems_kvm-x86_64' in my case. And then I can run the image in QEMU with `sudo qemu-system-x86_64 -fsdev local,id=myid,path=guest_fs,security_model=none -device virtio-9p-pci,fsdev=myid,mount_tag=fs0 -m 4G --kernel build/06-adding-filesystems_kvm-x86_64 -nodefaults -nographic -vga none --device sga -s -serial stdio --enable-kvm -cpu host`. In this command, the system-wide QEMU installation is used, but for the evaluation I used a manually built QEMU executable, and used it instead of the 'qemu-system-x86_64', but the command should the be same or similar. (A bit further I describe how I launched a manually built QEMU executable for the virtiofs benchmarks. Here I used the same method for evaluation).

To launch the benchmarks on native Linux, I used this same repo but built it with `gcc` command instead of `make`. This is possible because I used C macros guards (`#ifdef __linux__` or `#ifdef __Unikraft__`) in code (/src/) to guard Unikraft- or Linux-specific code.
The command to build the benchmarks for Linux is: 
`gcc -Wall src/main.c src/helper_functions.c src/measurement_scenarios.c src/scenario_runners.c src/time_functions.c -lm -o 9p_measure`. It creates a `9p_measure` executable in the same folder, which contains all the benchmarks compiled for Linux. And then the command for running the executable would be `./9p_measure`.

The benchmark code for virtiofs differs because as you mentioned, the vfscore integration of virtiofs is incomplete and I have to call the ukfuse API instead of the vfscore API and I have to do it not from the application code (/src/ directory in the 9p case), but rather from the unikernel code. For that reason I created a separate microlibrary in /lib/ called benchmarks. The code for this lies in the [virtiofs_unikraft](https://github.com/astrynzha/virtiofs_unikraft/tree/master/lib/benchmarks) repo.
To launch these benchmarks I first built a QEMU fork of the virtiofs project, which can be found [here](https://gitlab.com/virtio-fs/qemu) and the instructions on how to build it can be found [here](https://virtio-fs.gitlab.io/howto-qemu.html). In order to work properly, the virtiofs device in QEMU requires the "virtiofsd" daemon to run. This daemon is build together with the QEMU fork and can be found in its /build/ directory after the build.
In total, I ran the virtiofs benchmarks with this method:
1. build the unikernel containing the benchamarks by executing `make menuconfig` and `make` in the [virtiofs_unikraft](https://github.com/astrynzha/virtiofs_unikraft/tree/master) repo directory.
2. build QEMU. (For virtiofs-DAX I used the fork version of QEMU. And for virtiofs-FUSE and 9pfs I used the upstream QEMU).
3. launch virtiofsd daemon with the following command `sudo ./virtiofsd -o vhost_user_socket=/tmp/vhostqemu10 -o source=/home/andrii/Github/unikraft-andrii/test_dir -o cache=always -f`
(I might have used slightly different options to get the exact results in the evaluation, but this command should work.)
'./virtiofsd' can be found somewhere in the /build/ folder of QEMU.
'source=/home/andrii/Github/unikraft-andrii/test_dir' is a path to the directory where the benchmarks would be run. I also mounted tmpfs on this directory with `sudo mount -t tmpfs -o size=2G tpfs test_dir` (or any other size).
4. launch QEMU with the unikernel image from the step 1 (which contains the benchmarks) using the following command `sudo x86_64-softmmu/qemu-system-x86_64 --kernel ../../../../virtiofs_unikraft/unikraft/build/unikraft_kvm-x86_64 -nodefaults -nographic -vga none -machine graphics=off -s -serial stdio -chardev socket,id=char0,path=/tmp/vhostqemu10 -device vhost-user-fs-pci,queue-size=1024,chardev=char0,tag=myfs,cache-size=2G -m 4G -object memory-backend-file,id=mem,size=4G,mem-path=/dev/shm,share=on -numa node,memdev=mem --enable-kvm -cpu host`.
Here 'x86_64-softmmu/qemu-system-x86_64' is the built QEMU executable and can be found somewhere in QEMU's /build/ folder. And '../../../../virtiofs_unikraft/unikraft/build/unikraft_kvm-x86_64' is a relative path to the unikernel image from the step 1. Socket '/tmp/vhostqemu10' has to match in commands from step 3 and 4. (If I remember correctly, virtiofsd and QEMU with the virtiofs device communicate through this socket).
'-m 4G' and other sizes can be adjusted for measurements. '-m 4G' is the size of RAM that QEMU (or the unikernel image) gets. And if I am not mistaken, 'cache-size=2G' is the size of the DAX window. [This](https://virtio-fs.gitlab.io/howto-qemu.html) page has some more description of the options.

And whether to measure virtiofs file operations through FUSE or through DAX, that can be adjusted in the unikraft/lib/benchmarks/bench_tests.c file of the [virtiofs_unikraft](https://github.com/astrynzha/virtiofs_unikraft/tree/master) unikernel.

The unikernel can be also debugged with the QEMU -S option.

**Comment by astrynzha** [comment]
With regards to your second question. The idea was to have this libvirtiofs component as an integration link between the vfscore and the ukfuse (Figure 4.2). But I did not implement the ukfuse integration into the virtiofs due to time constraints. So I am not very familiar with the vfscore feature set and would be little of help here. But your understanding is correct, the integration of the ukfuse into the vfscore is missing and that is exactly the reason why the benchmarks use virtiofs through the ukfuse API.

![image](https://github.com/astrynzha/unikraft_9p_measure/assets/48807494/f0279b3b-08d2-4476-b277-91ff724ea1d3)


Let me know if you have any other questions.

**Comment by mmisono** [comment]
Thank you very much for your detailed and rapid response!
I managed to run virtiofs, and will try to look into a detail.

**Comment by astrynzha** [comment]
No problem! If you have got any other questions, let me know.
